# Generated by Django 2.2.5 on 2019-09-21 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название папки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания папки')),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.Folder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название изображения')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание изображения')),
                ('content', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('mime', models.CharField(max_length=32, verbose_name='MIME-тип источника')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ключ изображения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки изображения')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_parts', to='core.Folder', verbose_name='Папка с изображением')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('id',),
            },
        ),
    ]
