# Generated by Django 2.2.5 on 2019-09-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190921_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Описание изображения'),
        ),
    ]
